### ISSUE TITLE
Rules for capitalization in titles

### ISSUE THREAD

**Issue by WestonThayer** [jstych/zapier-style-guide#13]
Should our titles/headings be [title case](https://experience.sap.com/files/guidelines/References/text_cap.htm) or sentence case?

> Connect your apps and automate your workflows

or

> Connect Your Apps and Automate Your Workflows

**Comment by jstych** [comment]
@WestonThayer this PR should get you what you're looking for: https://github.com/jstych/zapier-style-guide/pull/16 😄  I'm going to have Melanie review this, too, before I merge it.
